name: Release
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      uses: gytis/maven-release-action@master
      with:
        email: gytis@redhat.com
        profiles: release
