name: Release

on: push

jobs:
  release:
    if: ${{startsWith(github.ref, 'refs/tags/release-')}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world at ${GITHUB_REF}!
