name: Release

on: push

jobs:
  release:
    if: ${{startsWith(github.ref, 'refs/tags/release-')}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      run: echo "::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | sed 's/refs\/tags\/release-//')"
    - name: Setup Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Prepare release
      run: |
        git config --local user.email "gytis@redhat.com"
        git config --local user.name "Gytis Trikleris"
        mvn release:prepare -B -DreleaseVersion=${{ env.RELEASE_VERSION }}
    - name: Perform release
      run: mvn release:perform -B
