name: Release

on: push

jobs:
  release:
    if: ${{startsWith(github.ref, 'refs/tags/release-')}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get release version
      run: echo "::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | sed 's/refs\/tags\/release-//')"
    - name: Print release version
      run: echo "Gonna release ${{ env.RELEASE_VERSION }}!"
